# Generated by Django 4.0.3 on 2024-03-27 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customer_address_alter_customer_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_makes_order',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer_makes_order',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.orders'),
        ),
    ]
