# Generated by Django 4.0.3 on 2024-03-28 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_customer_makes_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_agent',
            name='d_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery_agent',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.orders'),
        ),
    ]
