# Generated by Django 4.0.3 on 2024-03-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_delivery_agent_d_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_received',
            new_name='amount',
        ),
    ]
